CONFIG:
  API_KEY: ${OPENAI_API_KEY}  # Will be loaded from environment variable
  OPENAI_MODEL: 'gpt-4o-mini'
  DEFAULT_EXTENSION_TIME: 120
  SHEETS:
    BACKEND: 'backend'
    SYSTEM_PROMPT: 'prompting'
    OUTPUT: 'Output mẫu'

  SHEETS_RANGES:
    SYSTEM_PROMPT:
      DETECT_WARM_LEAD_WRAP_SYSTEM_PROMPT: 'B1'
      SUG_SCORING_WARM_UP_SYSTEM_PROMPT: 'C1'
      SUG_SCORING_LEAD_IN_SYSTEM_PROMPT: 'D1'
      SUG_SCORING_WRAP_UP_SYSTEM_PROMPT: 'E1'
      DETECT_VOCAB_PRONUN_GRAMMAR_SYSTEM_PROMPT: 'B2'
      SUG_SCORING_VOCAB_SYSTEM_PROMPT: 'C2'
      SUG_SCORING_PRONUN_SYSTEM_PROMPT: 'D2'
      SUG_SCORING_GRAMMAR_SYSTEM_PROMPT: 'E2'
      DETECT_ICQS_CCQS_SYSTEM_PROMPT: 'B3'
      SUG_SCORING_ICQS_SYSTEM_PROMPT: 'C3'
      SUG_SCORING_CCQS_SYSTEM_PROMPT: 'D3'

    BACKEND:
      TRANSCRIPTION: 'A2'
      DETECTED_JSON:
        DETECT_WARM_LEAD_WRAP_SECTION: 'C2'
        DETECT_VOCAB_PRONUN_GRAMMAR_SECTION: 'C6'
        DETECT_ICQS_CCQS_SECTION: 'C12'
      
      EXTENDED_TRANSCRIPTION:
        WARM_UP: 'D2'
        LEAD_IN: 'D3'
        WRAP_UP: 'D4'
        TEACHING_VOCAB_PRONUN_GRAMMAR_1: 'D6'
        TEACHING_VOCAB_PRONUN_GRAMMAR_2: 'D7'
        TEACHING_VOCAB_PRONUN_GRAMMAR_3: 'D8'
        TEACHING_VOCAB_PRONUN_GRAMMAR_4: 'D9'
        TEACHING_VOCAB_PRONUN_GRAMMAR_5: 'D10'
        TEACHING_VOCAB_PRONUN_GRAMMAR_6: 'D11'
        TEACHING_ICQS_CCQS_1: 'D12'
        TEACHING_ICQS_CCQS_2: 'D13'
        TEACHING_ICQS_CCQS_3: 'D14'
        TEACHING_ICQS_CCQS_4: 'D15'
        TEACHING_ICQS_CCQS_5: 'D16'

      SUG_SCORING:
        WARM_UP: 'E2'
        LEAD_IN: 'E3'
        WRAP_UP: 'E4'
        TEACHING_VOCAB_1: 'E6'
        TEACHING_GRAMMAR_1: 'F6'
        TEACHING_PRONUN_1: 'G6'
        TEACHING_VOCAB_2: 'E7'
        TEACHING_GRAMMAR_2: 'F7'
        TEACHING_PRONUN_2: 'G7'
        TEACHING_VOCAB_3: 'E8'
        TEACHING_GRAMMAR_3: 'F8'
        TEACHING_PRONUN_3: 'G8'
        TEACHING_VOCAB_4: 'E9'
        TEACHING_GRAMMAR_4: 'F9'
        TEACHING_PRONUN_4: 'G9'
        TEACHING_VOCAB_5: 'E10'
        TEACHING_GRAMMAR_5: 'F10'
        TEACHING_PRONUN_5: 'G10'
        TEACHING_VOCAB_6: 'E11'
        TEACHING_GRAMMAR_6: 'F11'
        TEACHING_PRONUN_6: 'G11'
        TEACHING_ICQS_1: 'E12'
        TEACHING_CCQS_1: 'F12'
        TEACHING_ICQS_2: 'E13'
        TEACHING_CCQS_2: 'F13'
        TEACHING_ICQS_3: 'E14'
        TEACHING_CCQS_3: 'F14'
        TEACHING_ICQS_4: 'E15'
        TEACHING_CCQS_4: 'F15'
        TEACHING_ICQS_5: 'E16'
        TEACHING_CCQS_5: 'F16'

    OUTPUT:
      DETECTED_JSON:
        DETECT_WARM_LEAD_WRAP_SECTION: 'E2'
        DETECT_VOCAB_PRONUN_GRAMMAR_SECTION: 'E6'
        DETECT_ICQS_CCQS_SECTION: 'E12'
      
      SUG_SCORING:
        WARM_UP: 'F3'
        LEAD_IN: 'F4'
        WRAP_UP: 'F5'
        TEACHING_VOCAB_1: 'F7'
        TEACHING_GRAMMAR_1: 'G7'
        TEACHING_PRONUN_1: 'H7'
        TEACHING_VOCAB_2: 'F8'
        TEACHING_GRAMMAR_2: 'G8'
        TEACHING_PRONUN_2: 'H8'
        TEACHING_VOCAB_3: 'F9'
        TEACHING_GRAMMAR_3: 'G9'
        TEACHING_PRONUN_3: 'H9'
        TEACHING_VOCAB_4: 'F10'
        TEACHING_GRAMMAR_4: 'G10'
        TEACHING_PRONUN_4: 'H10'
        TEACHING_VOCAB_5: 'F11'
        TEACHING_GRAMMAR_5: 'G11'
        TEACHING_PRONUN_5: 'H11'
        TEACHING_VOCAB_6: 'F12'
        TEACHING_GRAMMAR_6: 'G12'
        TEACHING_PRONUN_6: 'H12'
        TEACHING_ICQS_1: 'F13'
        TEACHING_CCQS_1: 'G13'
        TEACHING_ICQS_2: 'F14'
        TEACHING_CCQS_2: 'G14'
        TEACHING_ICQS_3: 'F15'
        TEACHING_CCQS_3: 'G15'
        TEACHING_ICQS_4: 'F16'
        TEACHING_CCQS_4: 'G16'
        TEACHING_ICQS_5: 'F17'
        TEACHING_CCQS_5: 'G17'

  TIME_ZONE: 'Asia/Ho_Chi_Minh'