version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./backend
        target: /app
      - type: bind
        source: ./backend/database
        target: /app/database
    ports:
      - "25035:3000"
    environment:
      - FLASK_ENV=development

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./frontend
        target: /app
    ports:
      - "25036:5000"